force-app/main/default/objects/Garnish__c/Garnish__c.object-meta.xml
<CustomObject>
    <label>Garnish</label>
    <nameField>
        <label>Garnish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garnishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Garnish__c/fields/Calories__c.field-meta.xml
<CustomField>
    <fullName>Calories__c</fullName>
    <label>Calories</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garnish__c/fields/Liquid__c.field-meta.xml
<CustomField>
    <fullName>Liquid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Liquid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/junc__c/junc__c.object-meta.xml
<CustomObject>
    <label>junc</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>junc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/junc__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/junc__c/fields/Garnish__c.field-meta.xml
<CustomField>
    <fullName>Garnish__c</fullName>
    <label>Garnish</label>
    <referenceTo>Garnish__c</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/testGarnishInfo.cls
@isTest

private class testGarnishInfo {

    static testMethod void myUnitTest() {
        Test.setMock(HttpCalloutMock.class, new MockGenerator());
        Account acc=new Account(Name='test');
        insert acc;
        Contact c=new Contact(AccountId=acc.Id,FirstName='First',LastName='Last',Email='abc@def.com');
        insert c;
        Garnish__c g= new Garnish__c(Name='Mozzarella',Calories__c=250,Color__c='Brown',Liquid__c=false,Origin__c='Brazil'); 
        insert g;
        junc__c j = new junc__c(Contact__c=c.Id,garnish__c=g.Id);
        insert j;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.addHeader('httpMethod', 'GET');
        req.requestUri = '/services/apexrest/Garnish/Mozzarella';       

        Test.startTest();
          List<contact> testCon=GarnishInfo.getContactByGarnish();
          System.debug(testCon);
        Test.stopTest();
   }

}