force-app/main/default/objects/Garnish__c/Garnish__c.object-meta.xml
<CustomObject>
    <label>Garnish</label>
    <nameField>
        <label>Garnish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garnishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/junc__c/junc__c.object-meta.xml
<CustomObject>
    <label>junc</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>junc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/junc__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/junc__c/fields/Garnish__c.field-meta.xml
<CustomField>
    <fullName>Garnish__c</fullName>
    <label>Garnish</label>
    <referenceTo>Garnish__c</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GarnishInfo.cls
@RestResource(urlMapping='/Garnish/*')
global with sharing class GarnishInfo {
    @HttpGet
    global static list<Contact> getContactByGarnish() {
        RestRequest request = RestContext.request;
        // grab the cheese from the end of the URL
        System.debug(request);
        String garnish = request.requestURI.substring(
          request.requestURI.lastIndexOf('/')+1);
        System.debug('Garnish is '+garnish);
        Id id=[SELECT Id FROM Garnish__c where Name=: garnish].Id;
        list<junc__c> relatedContacts = [SELECT Contact__c FROM junc__c WHERE Garnish__c =: Id];
        list<Id> contactIds= new list<Id>();
        for(junc__c j:relatedContacts){
            contactIds.add(j.Contact__c);
        }
        list<Contact> cons=[SELECT Id,Name,AccountId FROM Contact Where Id IN: contactIds];
        return cons;
    }
}