force-app/main/default/objects/Garnish__c/Garnish__c.object-meta.xml
<CustomObject>
    <label>Garnish</label>
    <nameField>
        <label>Garnish Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garnishes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/junc__c/junc__c.object-meta.xml
<CustomObject>
    <label>junc</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>junc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>juncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/junc__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/junc__c/fields/Garnish__c.field-meta.xml
<CustomField>
    <fullName>Garnish__c</fullName>
    <label>Garnish</label>
    <referenceTo>Garnish__c</referenceTo>
    <relationshipLabel>juncs</relationshipLabel>
    <relationshipName>juncs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactInfo.cls
@RestResource(urlMapping='/ContactInfo')
global with sharing class ContactInfo{
  @HttpPost
    global static Id createContact(String id, String accountId, String email, String firstName, String lastName,String[] garnish) {
        Contact c=new Contact();
        String owner=[SELECT OwnerId FROM Account WHERE Id=:accountId].OwnerId;
        Date today = Date.today();
        list<Garnish__c> garnishIDs=[SELECT Id FROM Garnish__c WHERE Name IN: garnish];
        System.debug('Garnish Ids '+garnishIDs);
        list<junc__c> j=new list<junc__c>();
        
        //If Contact Id is not supplied
        if(id==''){
            //create New
            c.AccountId=accountId;
            c.FirstName=firstName;
            c.LastName=lastName;
            c.Email=email;
            insert c;
            for(Garnish__c gId:garnishIds){
                junc__c ju= new junc__c(contact__c=c.Id,garnish__c=gId.Id);
                j.add(ju);
            }
            insert j;
            
            Task t=new Task(OwnerId=owner,ActivityDate=today + 2,Status='In Progress',Subject='Get in Touch',WhatId=accountId,WhoId=c.Id);
            insert t;
        }
        //If Contact id is present
        else{
            //Search and check for old and update
            if((id.length() == 15 || id.length() == 18) && Pattern.matches('^[a-zA-Z0-9]*$', id)){
                c=[SELECT Id,AccountId,FirstName,LastName FROM Contact WHERE ID =:Id];
                c.AccountId=accountId;
                c.Email=email;
                c.FirstName=firstName;
                c.LastName=lastName;
                update c;
                for(Garnish__c gId:garnishIds){
                    junc__c ju= new junc__c(contact__c=c.Id,garnish__c=gId.Id);
                    j.add(ju);
                }
                insert j;
                
                Task t=new Task(OwnerId=owner,ActivityDate=today + 2,Status='In Progress',Subject='Get in Touch',WhatId=accountId,WhoId=c.Id);
                insert t;
            }
            else{
                    //bad Id
            }
        }

        return c.Id;
    }   
}