force-app/main/default/objects/Audit_History__c/Audit_History__c.object-meta.xml
<CustomObject>
    <label>Audit History</label>
    <nameField>
        <label>Audit History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_History__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/Old_value__c.field-meta.xml
<CustomField>
    <fullName>Old_value__c</fullName>
    <label>Old value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuditHistoryController.cls
public with sharing class AuditHistoryController {
    
    @AuraEnabled
    public static List<Audit_History__c> getAuditHistoryRecords(String oppProductId){

        List<Audit_History__c> auditList = [SELECT 
                                                Id, Field_Name__c, New_Value__c,Old_value__c, 
                                                CreatedDate, owner.name
                                            FROM Audit_History__c
                                            WHERE Record_Id__c = :oppProductId 
                                            ORDER BY CreatedDate DESC];
        if(auditList.isEmpty()){
            throw new AuraHandledException('No Audit History Found');
        }

        return auditList;
    }
}