force-app/main/default/objects/Audit_History__c/Audit_History__c.object-meta.xml
<CustomObject>
    <label>Audit History</label>
    <nameField>
        <label>Audit History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_History__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/Old_value__c.field-meta.xml
<CustomField>
    <fullName>Old_value__c</fullName>
    <label>Old value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_History__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemHandler.cls
public with sharing class OpportunityLineItemHandler implements Itrigger{
    
    public void bulkBefore(){

    } 
    public void bulkAfter(){

    } 
    public void beforeInsert(List<SObject> newlstObj){
    
    } 
    public void beforeUpdate(List<SObject> newlstObj,List<SObject> oldlstObj,Map<Id,SObject> newMapObj, Map<Id,SObject> oldMapObj){

    } 
    public void beforeDelete(List<SObject> oldlstObj,Map<Id,SObject> oldMapObj){
        
    } 
    public void afterInsert(List<SObject> newlstObj, Map<Id,SObject> newMapObj){

    } 
    public void afterUpdate(List<SObject> newlstObj,List<SObject> oldlstObj,Map<Id,SObject> newMapObj, Map<Id,SObject> oldMapObj){
        insertAuditHistory((Map<Id, OpportunityLineItem>)oldMapObj, (Map<Id, OpportunityLineItem>)newMapObj);
    } 
    public void afterDelete(List<SObject> oldlstObj,Map<Id,SObject> oldMapObj){
    
    }
    public void andFinally(){

    }

    public static void insertAuditHistory(Map<Id,OpportunityLineItem> oldMapObj, Map<Id,OpportunityLineItem> newMapObj){

        List<Audit_History__c> insertAuditHistory = new List<Audit_History__c>();
        for(OpportunityLineItem ol : newMapObj.values()){
            if(ol.UnitPrice != oldMapObj.get(ol.Id).UnitPrice){
                Audit_History__c auditHist = new Audit_History__c();
                auditHist.Record_Id__c = ol.Id;
                auditHist.Field_Name__c = 'Sales Price';
                auditHist.Object_Name__c = 'Opportunity Product';
                auditHist.Old_Value__c = String.valueOf(oldMapObj.get(ol.Id).UnitPrice);
                auditHist.New_Value__c = String.valueOf(ol.UnitPrice);
                insertAuditHistory.add(auditHist);
            }
        }

        insert insertAuditHistory;
    }
}