force-app/main/default/objects/Pharma_Product__c/Pharma_Product__c.object-meta.xml
<CustomObject>
    <label>Pharma Product</label>
    <nameField>
        <label>Pharma Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharma Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pharma_Product__c/fields/Account_id__c.field-meta.xml
<CustomField>
    <fullName>Account_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pharma Products</relationshipLabel>
    <relationshipName>Pharma_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/pharmamaxinventorybyaccount.cls
public class pharmamaxinventorybyaccount {
    public static void pharmamaxinventorybyacc(){
        map<id,List<integer>> pharmamap = new map<id,List<integer>>();
        list<decimal> pharmalist = new list<decimal>();
        for(Pharma_Product__c pharma :[select id,Account_id__c,Inventory__c from Pharma_Product__c]){
            if(pharmamap.containsKey(pharma.Account_id__c) ) {
                                  List<integer> inventory = pharmamap.get(pharma.Account_id__c);
                inventory.add(integer.valueof(pharma.Inventory__c));

                pharmamap.put(pharma.Account_id__c, inventory);  
                if(integer.valueOf(pharmamap.get(pharma.Account_id__c))>integer.valueOf(pharmamap.get(pharma.Account_id__c))){

                pharmamap.put(pharma.Account_id__c, inventory);  
                }   
            } else {
                pharmamap.put(pharma.Account_id__c, new List<integer> { integer.valueof(pharma.Inventory__c) });
            }
            
        }
        system.debug(pharmamap);
    }
}